### ISSUE TITLE
Cannot load_all() 

### ISSUE THREAD

**Issue by fontikar** [fontikar/mvabund#2]
Re-compiling mvabund
─  installing *source* package ‘mvabund’ ...
   ** using staged installation
   ** libs
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppGSL/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   In file included from RcppExports.cpp:5:
   In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppGSL/include/RcppGSL.h:25:
   /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppGSL/include/RcppGSLForward.h:25:10: fatal error: 'gsl/gsl_vector.h' file not found
   #include <gsl/gsl_vector.h> 
            ^~~~~~~~~~~~~~~~~~
   1 error generated.
   make: *** [RcppExports.o] Error 1
   ERROR: compilation failed for package ‘mvabund’
─  removing ‘/private/var/folders/fk/9s3srn850qj90zp4t67zc0fm0000gq/T/RtmpRycsUY/devtools_install_f34412103db/mvabund’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occurred
In addition: Warning message:
No 'gsl-config' config script found, limiting extensibility.  

Not sure where I can get these files got gsl/gsl-config.
I tried to install via homebrew and update Rccpgsl - no luck! 

I will not worry for now! Can still make vignettes for now!

**Comment by fontikar** [comment]
I've tried googling for the gsl_vector.h file and adding it in manually but then it error refers to another file! 

I've tried updating RcppGSL on my computer and then restarting Rstudio but this doesn't seem to fix it as updating the package doesn't add the "missing" files necessary

**Comment by fontikar** [comment]
I've also tried git checking out previous commits but the error remains but I expected it so since my R library is not affected by the commit history! Worth a try though!

**Comment by dfalster** [comment]
Hi @fontikar 

I got the same error as you when installing on my laptop. But it install fine on my desktop, which is also running R 4.1 and OSX. Further, mid desktop has GSL installed at `/usr/local/` and i noticed this being called during the compile:

```
Running /Library/Frameworks/R.framework/Resources/bin/R CMD INSTALL /var/folders/_q/vq6sxzjx64b5yb1_zjbh7xzm0000gp/T//Rtmp8RUjiO/mvabund_4.2.1.tar.gz \
  --install-tests 
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library’
* installing *source* package ‘mvabund’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppGSL/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppGSL/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c Rinterface.cpp -o Rinterface.o
...
...
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppGSL/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c summary.cpp -o summary.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o mvabund.so RcppExports.o Rinterface.o anova.o calctest.o glm.o glmtest.o io.o rnd.o simutility.o summary.o -L/usr/local/lib -lgsl -lgslcblas -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-mvabund/00new/mvabund/libs
** R
** data
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mvabund)
```

So I wonder if you need to install the GSL library on your machine, in addition to RcppGSL?? 
I would have imagined the idea of RcppGSL is to avoid installing GSL elsewhere. But RcppGSL doesn't include the file `gsl_vector.h` so not sure how that's going to work.

**Comment by dfalster** [comment]
Ah yes, see the system requirements for RcppGSL - so you do need to have GSL installed before you can successfully use RcppGSL or anything depending on it

https://github.com/eddelbuettel/rcppgsl/blob/0c8cd727dda2a87f45db38e49ec4ac23a47f1113/DESCRIPTION#L24

```
SystemRequirements: GNU GSL
```

Suggests this should also be in mvabund

**Comment by fontikar** [comment]
Homebrew installed gsl in `opt/homebrew/cellar/` which is strange! How did you install your GSL library @dfalster? 
I tried to create a symlink between `usr/local/include` and where gsl is located and the package seems to be able to load ( displayed in sessionInfo() ) but still throwing errors 

```Error in dyn.load(dll_copy_file) : 
  unable to load shared object '/var/folders/fk/9s3srn850qj90zp4t67zc0fm0000gq/T//RtmpND20ba/pkgload1611e7a14ffca/mvabund.so':
  dlopen(/var/folders/fk/9s3srn850qj90zp4t67zc0fm0000gq/T//RtmpND20ba/pkgload1611e7a14ffca/mvabund.so, 0x0006): symbol not found in flat namespace '_gsl_rng_default'
In addition: Warning message:
No 'gsl-config' config script found, limiting extensibility. 
```

**Comment by dfalster** [comment]
I try to keep home-brew off my machine!

Here's what i do

1. download direct from source at https://www.gnu.org/software/gsl/ (points to https://mirror.ibcp.fr/pub/gnu/gsl/gsl-latest.tar.gz)
2. Unpack (double click in finder)
3. open terminal, `cd gsl-2.7.1`
4. run `./configure`
5. run `sudo make install`
6. make sure the place installed (for me `/usr/local/include`) is in default path for terminal , so that it can find it

**Comment by fontikar** [comment]
Oh interesting! Is there a reason to avoid homebrew? It seems like a such a great way to install various tools! Will try your method now! :) Thanks @dfalster

**Comment by dfalster** [comment]
You can keep the home-brew method if you like.Just need to add homebrew folder to default path in terminal

I found it was overkill, all i need is one package! Mac OSX has a lot of tool included in home-brew included by default

**Comment by fontikar** [comment]
SUCESSS just another error! For another issue ;) Thanks @dfalster!

**Comment by fontikar** [comment]
I am still unable to load_all() the package despite installing gsl in the right location. 

I've tried the following: 
1) Reclone my forked repo and see if load_all() works --> NO 
2) Cloned the original repo, load_all() still failing 
3) Tried installing  mvabund at the main branch from the original repo --> install failed. 

The error I am getting in all 1-3 contexts below is: 
```Error: package or namespace load failed for ‘mvabund’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/private/var/folders/fk/9s3srn850qj90zp4t67zc0fm0000gq/T/Rtmpqu1bw1/mvabund.Rcheck/00LOCK-mvabund/00new/mvabund/libs/mvabund.so':
  dlopen(/private/var/folders/fk/9s3srn850qj90zp4t67zc0fm0000gq/T/Rtmpqu1bw1/mvabund.Rcheck/00LOCK-mvabund/00new/mvabund/libs/mvabund.so, 0x0006): symbol not found in flat namespace '_gsl_rng_default'```

At this stage I don't know if getting the package to install/load is important to the goal of contributing to the vignettes for mvabund! Will update David accordingly!

**Comment by fontikar** [comment]
Installing the correct R version for my M1 mac solved this issue!
