### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by fontikar** [fontikar/mvabund#3]
Upon running check() 

```hecking package dependencies ... ERROR
  There is circular dependency in the installation order:
    One or more packages in
    'Rcpp', 'MASS', 'methods', 'stats', 'tweedie', 'statmod', 'parallel',
    'ecostats', 'RcppGSL', 'utils', 'grDevices', 'graphics', 'ecoCopula',
    'GET', 'mgcv', 'mvtnorm', 'glasso', 'plyr', 'sna', 'igraph',
    'betareg', 'doParallel', 'glm2', 'ordinal', 'compiler', 'foreach',
    'cluster', 'ggplot2', 'gridExtra', 'viridisLite', 'nlme', 'Matrix',
    'splines', 'statnet.common', 'network', 'magrittr', 'pkgconfig',
    'rlang', 'flexmix', 'Formula', 'lmtest', 'modeltools', 'sandwich',
    'iterators', 'ucminf', 'numDeriv', 'codetools', 'digest', 'glue',
    'grid', 'gtable', 'isoband', 'scales', 'tibble', 'withr', 'lattice',
    'coda', 'tools', 'nnet', 'stats4', 'zoo', 'farver', 'labeling',
    'lifecycle', 'munsell', 'R6', 'RColorBrewer', 'ellipsis', 'fansi',
    'pillar', 'vctrs', 'colorspace', 'cli', 'utf8'
    depend on this package (for the versions on the repositories).
```

@dwarton any idea which package in this list depends/suggests/imports  mvabund

**Comment by dwarton** [comment]
ecostats is the issue


From: Fonti Kar ***@***.***>
Sent: Friday, 22 July 2022 3:22 PM
To: fontikar/mvabund ***@***.***>
Cc: David Warton ***@***.***>; Mention ***@***.***>
Subject: [fontikar/mvabund] Circular dependency (Issue #3)


Upon running check()

  There is circular dependency in the installation order:

    One or more packages in

    'Rcpp', 'MASS', 'methods', 'stats', 'tweedie', 'statmod', 'parallel',

    'ecostats', 'RcppGSL', 'utils', 'grDevices', 'graphics', 'ecoCopula',

    'GET', 'mgcv', 'mvtnorm', 'glasso', 'plyr', 'sna', 'igraph',

    'betareg', 'doParallel', 'glm2', 'ordinal', 'compiler', 'foreach',

    'cluster', 'ggplot2', 'gridExtra', 'viridisLite', 'nlme', 'Matrix',

    'splines', 'statnet.common', 'network', 'magrittr', 'pkgconfig',

    'rlang', 'flexmix', 'Formula', 'lmtest', 'modeltools', 'sandwich',

    'iterators', 'ucminf', 'numDeriv', 'codetools', 'digest', 'glue',

    'grid', 'gtable', 'isoband', 'scales', 'tibble', 'withr', 'lattice',

    'coda', 'tools', 'nnet', 'stats4', 'zoo', 'farver', 'labeling',

    'lifecycle', 'munsell', 'R6', 'RColorBrewer', 'ellipsis', 'fansi',

    'pillar', 'vctrs', 'colorspace', 'cli', 'utf8'

    depend on this package (for the versions on the repositories).

@dwarton<https://github.com/dwarton> any idea which package in this list depends/suggests/imports mvabund

**Comment by fontikar** [comment]
Thanks @dwarton nice spot! My brain stopped working when I had to spot the odd one out! I have moved ecostats in to a Suggest field to deal with circular dependency. This doesn't affect the vignettes, users can still install ecostats if they use: 
install.packages("ecostats", dependencies = TRUE).    55ade65
