### ISSUE TITLE
pkgdown cannot render via GitHub Pages

### ISSUE THREAD

**Issue by fontikar** [fontikar/mvabund#4]
Locally on my computer, the pkgdown site renders beautifully
![Screen Shot 2022-07-28 at 1 22 46 pm](https://user-images.githubusercontent.com/12161802/181413545-0f3547ca-a327-4d48-9987-521d38729237.png)

Website is not rendering as Github pages - https://fontikar.github.io/mvabund/
![Screen Shot 2022-07-28 at 1 23 23 pm](https://user-images.githubusercontent.com/12161802/181413592-4e4efa56-0a0e-4d01-af21-fc7032a30b36.png)

I thought it may have to do with whether the site the in development or released mode: https://pkgdown.r-lib.org/articles/how-to-update-released-site.html 

But doesn't seem to be as my other pkgdown projects are all set to "auto"

@dfalster do you have any ideas about this? Google with no success as I don't know what to refer to the 'unrendered, bare bones' state. Thank you in advance!!!

**Comment by fontikar** [comment]
I've just tried a few things:
1) Deleted the contents of the docs/ folder, rebuild and commit and push with no success
2) Un-publish site via GH pages settings and then republish it again, also with no success
3) Set development: development:  mode: release in the pkgdown.yml with no success
4) Set up a Github action for deploying but currently failing on building the site despite it building successfully locally https://github.com/fontikar/mvabund/runs/7602086024?check_suite_focus=true 

Next plan of action is to post of RStudio community and see what happens!

**Comment by fontikar** [comment]
Here is the link to RStudio community help: https://community.rstudio.com/t/pkgdown-website-builds-locally-but-only-partial-rendering-via-github-pages/143637

**Comment by dfalster** [comment]
Perhaps missing external GSL dependency in the Actions setup?

**Comment by fontikar** [comment]
I don't think its the GSL dependency for pkgdown site building. 

But thats a good call for [R CMD check Actions](https://github.com/fontikar/mvabund/actions/runs/2772151866) - I suspect thats why David is using the[ ci workflow ](https://github.com/fontikar/mvabund/actions/runs/2772151865)

**Comment by fontikar** [comment]
Its fixed after implementing a gh-pages branch to deploy to from GHA, via the r-lib/actionsactions. 

usethis::use_pkgdown_github_pages() sets this up properly.
